import PDFDocument from 'pdfkit';
import { User } from '../models/User.js';
import { getCategoryBreakdown, getPeriodOverview } from './reportService.js';
import { formatMoney } from '../utils/currency.js';

/**
 * Generate financial report PDF stream.
 * Honors report filters: month, dateFrom, dateTo, category, type.
 */
export const generateReportPdfStream = async (userId, res, filters = {}) => {
  const user = await User.findById(userId);
  const reportFilters = {
    type: filters.type || 'expense',
    month: filters.month,
    dateFrom: filters.dateFrom,
    dateTo: filters.dateTo,
    category: filters.category
  };
  const [overview, breakdown] = await Promise.all([
    getPeriodOverview(userId, reportFilters),
    getCategoryBreakdown(userId, reportFilters)
  ]);

  const periodLabel = overview.periodLabel;

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=CampusCoin_Report_${(filters.month || periodLabel || 'report').replace(/[^\w-]/g, '_')}.pdf`);

  doc.pipe(res);

  doc.rect(0, 0, doc.page.width, 80).fill('#4F46E5');
  doc.fillColor('#FFFFFF').fontSize(22).text('CAMPUS COIN - FINANCIAL REPORT', 50, 25);
  doc.fontSize(12).text(`Student Spending & Budget Overview (${periodLabel})`, 50, 52);

  doc.moveDown(3);
  doc.fillColor('#111827');

  doc.fontSize(14).text(`Student Name: ${user.name}`, { underline: false });
  doc.fontSize(11).text(`Email: ${user.email}`);
  doc.text(`Academic Year: ${user.academicYear}`);
  doc.text(`Report Period: ${periodLabel}`);
  doc.text(`Type Filter: ${reportFilters.type}`);
  if (filters.category) doc.text(`Category Filter: applied`);

  doc.moveDown();
  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(14).text('Period Overview');
  doc.moveDown(0.5);

  doc.fontSize(11);
  doc.text(`Total Income: ${formatMoney(overview.totals.income, user.currency)}`);
  doc.text(`Total Expense: ${formatMoney(overview.totals.expense, user.currency)}`);
  doc.text(`Net Balance: ${formatMoney(overview.totals.balance, user.currency)}`);
  doc.text(`Filtered Category Total: ${formatMoney(breakdown.total, user.currency)}`);

  doc.moveDown();
  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  doc.fontSize(14).text('Breakdown by Category');
  doc.moveDown(0.5);

  if (breakdown.categories.length === 0) {
    doc.fontSize(10).fillColor('#6B7280').text('No transactions recorded for this filtered period.');
  } else {
    doc.fontSize(10).fillColor('#374151');
    doc.text('Category', 50, doc.y, { width: 200, continued: true });
    doc.text('Total', { width: 150, continued: true });
    doc.text('Percentage', { width: 100 });
    doc.moveDown(0.5);

    breakdown.categories.forEach((cat) => {
      doc.fontSize(10).fillColor('#1F2937');
      doc.text(cat.name, 50, doc.y, { width: 200, continued: true });
      doc.text(`${formatMoney(cat.total, user.currency)}`, { width: 150, continued: true });
      doc.text(`${cat.percentage}%`, { width: 100 });
      doc.moveDown(0.3);
    });
  }

  doc.moveDown(3);
  doc.fontSize(9).fillColor('#9CA3AF').text('Generated by Campus Coin - Smart Spending Student Style.', 50, doc.page.height - 50, {
    align: 'center'
  });

  doc.end();
};
